#!/usr/bin/env node
/**
 * 编译 Standalone.sol（自包含，无 OpenZeppelin 依赖），
 * 输出 ABI + bytecode 到 src/lib/bytecode.ts
 */
import fs from "node:fs";
import path from "node:path";
import solc from "solc";

const ROOT = path.resolve(import.meta.dirname, "..");
const SRC = path.join(ROOT, "contracts/src/Standalone.sol");

const source = fs.readFileSync(SRC, "utf8");

const input = {
  language: "Solidity",
  sources: { "Standalone.sol": { content: source } },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    evmVersion: "paris",
    outputSelection: { "*": { "*": ["abi", "evm.bytecode.object"] } },
  },
};

const output = JSON.parse(solc.compile(JSON.stringify(input)));

if (output.errors) {
  const fatal = output.errors.filter((e) => e.severity === "error");
  if (fatal.length) {
    console.error(fatal.map((e) => e.formattedMessage).join("\n"));
    process.exit(1);
  }
}

function pick(name) {
  const c = output.contracts["Standalone.sol"][name];
  return { abi: c.abi, bytecode: "0x" + c.evm.bytecode.object };
}

const marketplace = pick("RWAMarketplace");
const token = pick("RWAToken");

const out = `// Auto-generated by scripts/compile.mjs — do not edit
export const MARKETPLACE_ABI = ${JSON.stringify(marketplace.abi, null, 2)} as const;
export const MARKETPLACE_BYTECODE = "${marketplace.bytecode}" as const;

export const RWAToken_ABI = ${JSON.stringify(token.abi, null, 2)} as const;
export const RwaToken_BYTECODE = "${token.bytecode}" as const;
`;

const OUT_PATH = path.join(ROOT, "src/lib/bytecode.ts");
fs.writeFileSync(OUT_PATH, out);
console.log("Wrote", OUT_PATH);
console.log("Marketplace bytecode length:", marketplace.bytecode.length);
console.log("RwaToken bytecode length:", token.bytecode.length);
